// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/layout/navigation/navigation.v1.component.ts
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import {Component, HostBinding, Inject, Input} from "@angular/core";
import {AbstractRoutedCoreComponent} from "../../AbstractRoutedCoreComponent";
import {BreadCrumbV2ItemModel} from "../breadcrumb/v2/breadcrumb.v2.component";
import {Route} from "@angular/router";
import {RoutedCoreComponentModel} from "../../model/RoutedCoreComponentModel";
import {NavigationItemModel} from "../../model/NavigationItemModel";
import {NAVIGATION_UTIL_SERVICE, NavigationUtilityService} from "../../services/NavigationUtilityService";

export interface NavigationV1Item extends NavigationItemModel{
    level: number,
    active: boolean,
    title: string,
    url: string,
    lastModified: number,
    description?: string,
    path: string,
    children?: NavigationV1Item[]
}

export interface NavigationV1Model extends RoutedCoreComponentModel{
    items:NavigationV1Item[]
    accessibilityLabel?: string
}

export function NavigationV1IsEmptyFn(props:NavigationV1Model): boolean{
    return props.items == null || props.items.length === 0;
}


@Component({
    selector: 'core-navigation-v1',
    templateUrl: './navigation.v1.component.html'
})
export class NavigationV1Component extends AbstractRoutedCoreComponent implements NavigationV1Model {

    @HostBinding('class') class = 'cmp-navigation';

    navigationUtilService: NavigationUtilityService;

    @Input() items: NavigationV1Item[];
    @Input() accessibilityLabel;

    constructor(@Inject(NAVIGATION_UTIL_SERVICE) navigationUtilService: NavigationUtilityService) {
        super();
        this.navigationUtilService = navigationUtilService;
    }

    get isEmpty(): boolean {
        return NavigationV1IsEmptyFn(this);
    }


    getItemCssClass(item:NavigationV1Item):string{
        const active:string = this.isItemActive(item) ? ` ${this.class}__item--active`: '';
        const level:string = ` ${this.class}__item--level-${item.level}`;
        return `${this.class}__item${active}${level}`;
    }

    /**
     * You may overrule this method to determine for example based on current URL / page context whether the item is active.
     * @param item
     */
    isItemActive(item:BreadCrumbV2ItemModel):boolean{
        return this.navigationUtilService.isItemActive(item);
    }
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="NavigationV1"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    
    <nav class="{{class}}"
         role="navigation"
         itemScope itemType="http://schema.org/SiteNavigationElement"
         [attr.aria-label]="accessibilityLabel">
        <ul class="{{class}}__group">
            <ng-container *ngFor="let childItem of items; let i = index">
                <ng-container [ngTemplateOutlet]="navigationItem" [ngTemplateOutletContext]="{item:childItem}"></ng-container>
            </ng-container>
        </ul>
    </nav>

</ng-template>

<ng-template #navigationGroup let-item='item'>
    <ul class="{{class}}__group">
        <ng-container *ngFor="let childItem of item.children; let i = index">
            <ng-container [ngTemplateOutlet]="navigationItem" [ngTemplateOutletContext]="{item:childItem}"></ng-container>
        </ng-container>
    </ul>
</ng-template>


<ng-template #navigationItem let-item='item'>
    <li [ngClass]="getItemCssClass(item)">
        <ng-container [ngTemplateOutlet]="navigationLink" [ngTemplateOutletContext]="{item:item}"></ng-container>
        <ng-container *ngIf="!!item.children && item.children.length > 0" [ngTemplateOutlet]="navigationGroup"
                      [ngTemplateOutletContext]="{item:item}"></ng-container>
    </li>
</ng-template>

<ng-template #navigationLink let-item='item'>
    <ng-container *ngIf="isItemRouted(item)" [ngTemplateOutlet]="routedLink" [ngTemplateOutletContext]="{item:item}"></ng-container>
    <ng-container *ngIf="!isItemRouted(item)" [ngTemplateOutlet]="staticLink" [ngTemplateOutletContext]="{item:item}"></ng-container>
</ng-template>


<ng-template #routedLink let-item='item'>
    <a class="{{class}}__item-link"
       title="{{item.title}}"
       routerLink="{{item.url}}"
       routerLinkActive="active"
       [attr.aria-current]="item.active">
        {{item.title}}
    </a>
</ng-template>

<ng-template #staticLink let-item='item'>
    <a class="{{class}}__item-link"
       title="{{item.title}}"
       href="{{item.url}}"
       [attr.aria-current]="item.active">
        {{item.title}}
    </a>
</ng-template>

// react/react-core/src/core/layout/navigation/v1/NavigationV1.tsx
import React from 'react';
import {AbstractCoreComponent, CoreComponentModel, CoreComponentState} from "../../../AbstractCoreComponent";
import {isItemRouted, RoutedCoreComponentModel, RoutedModel} from "../../../routing/RoutedCoreComponent";
import {RoutedLink} from "../../../routing/RoutedLink";



export interface NavigationV1Item extends RoutedModel{
    level: number,
    active: boolean,
    title: string,
    url: string,
    lastModified: number,
    description?: string,
    path: string,
    children?: NavigationV1Item[]
}

export interface NavigationV1Model extends RoutedCoreComponentModel{
    items:NavigationV1Item[]
    accessibilityLabel?: string
}

export function NavigationV1IsEmptyFn(props:NavigationV1Model): boolean{
    return props.items == null || props.items.length === 0;
}

export class NavigationV1<Model extends NavigationV1Model, State extends CoreComponentState> extends AbstractCoreComponent<Model, State> {

    public static defaultProps = {
        isInEditor: false,
        hidePlaceHolder: false,
        items: []
    };

    constructor(props:Model) {
        super(props, "cmp-navigation", 'NavigationV1');
    }

    isEmpty(): boolean{
        return NavigationV1IsEmptyFn(this.props);
    }

    determineIsActive(item:NavigationV1Item){
        return item.active;
    }

    renderComponent(){

        const selfClone:NavigationV1Item = {
            active: false,
            lastModified: 0,
            level: 0,
            path: "",
            title: "",
            url: "",
            children: this.props.items
        };

        return (
            <nav className={this.baseCssCls}
                 role="navigation"
                 itemScope itemType="http://schema.org/SiteNavigationElement"
                 aria-label={this.props.accessibilityLabel}>
                {this.renderGroup(selfClone)}
            </nav>
        )
    }

    renderGroup(item:NavigationV1Item){
        return (
            <>
                {!!item.children && item.children.length > 0 &&  (
                    <ul className={this.baseCssCls + '__group'}>
                        {item.children.map(
                            (item,index) => { return this.renderNavItem(item,index)}
                        )}
                    </ul>
                )}
           </>
        )
    }

    renderLink(item:NavigationV1Item, isActive:boolean){
        return (
            <RoutedLink isRouted={isItemRouted(this.props,item)} to={item.url} title={item.title} aria-current={isActive && 'page'}
               className={this.baseCssCls + '__item-link'}>{item.title}</RoutedLink>
        )
    }
    renderNavItem(item: NavigationV1Item, index: number) {
        const isActive = this.determineIsActive(item);
        const cssClass = this.baseCssCls + '__item ' +
                         this.baseCssCls + '__item--level-' + item.level + ' '
                         + ' ' + this.getExtraNavItemCssClss(item, index)
                         + (isActive ? ' ' + this.baseCssCls + '__item--active' : '');
        return (
            <li key={this.baseCssCls + '__item-' + index} className={cssClass}>
                    { this.renderLink(item, isActive) }
                    {
                        !!item.children && item.children.length > 0 && this.renderGroup(item)
                    }
            </li>
        )
    }

    getExtraNavItemCssClss(item: NavigationV1Item, index: number) {
        return "";
    }
}
