// react/react-core/src/core/button/v1/button.tsx
import React, {MouseEvent} from 'react';
import {ButtonV1Model} from "../../../types";
import {AbstractCoreComponent} from "../../AbstractCoreComponent";

export function isEmpty(props:ButtonV1Model): boolean{
    return props.text == null || props.text.length === 0;
}

export class Button<Model extends ButtonV1Model> extends AbstractCoreComponent<ButtonV1Model> {

    constructor(props:Model) {
        super(props);
        this.handleOnClick = this.handleOnClick.bind(this);
    }

    handleOnClick(event:MouseEvent){
        if(this.props.handleOnClick){
            this.props.handleOnClick(event);
        }
    }
    getContent(){
        return (
            <>
                { this.props.icon && <span className={'cmp-button__icon cmp-button__icon--' + this.props.icon}></span>  }
                <span className="cmp-button__text">{this.props.text}</span>
            </>
        );
    }

    isEmpty(): boolean{
        return isEmpty(this.props);
    }

    render(){

        const isEmpty:boolean = this.isEmpty();

        return (
            <>
                { !isEmpty &&
                    <div className="button" onClick={this.handleOnClick}>
                        {
                            this.props.link &&
                            <a aria-label={this.props.ariaLabel} className="cmp-button" href={this.props.link}>
                                {this.getContent()}
                            </a>
                        }
                        {   !this.props.link &&
                        <button className="cmp-button">
                            {this.getContent()}
                        </button>
                        }
                    </div>
                }
                {
                    this.__renderPlaceHolder('Contrib Button V1')
                }
            </>

        )
    }
};

// react/react-webcomponents/src/button/v1/Button.tsx
import React, { MouseEvent, Component } from 'react';

import {Button, ButtonV1Model} from "@adobe/core-contrib-core";

//@ts-ignore
import { createCustomElement, DOMModel, byContentVal, byAttrVal, registerEvent } from "@adobe/react-webcomponent";

interface SubModel extends ButtonV1Model{
    testProp?: string;
}

class ButtonSub extends Button<SubModel>{
    constructor(props:SubModel) {
        super(props);
    }
    getContent(){
        const el = super.getContent();
        return (<span>overridden! {el}</span>);
    }
}


class ButtonModel extends DOMModel {
    @byContentVal text: string = "something";
    @byAttrVal link?: string;
    @byAttrVal icon?: string;
}

class ReactButton extends Component<ButtonModel> {

    handleOnClick(event:MouseEvent){
        console.log("event", event);
        alert("captured!");
    }

    render() {
        return (
            <ButtonSub
                handleOnClick={this.handleOnClick}
                text={this.props.text}
                icon={this.props.icon}
                link={this.props.link}
            />
        )
    }
}

const ButtonCustomElement = createCustomElement(ReactButton, ButtonModel, "element");
window.customElements.define("core-button", ButtonCustomElement);
