// react/react-core/src/core/authoring/download/v1/DownloadV1.tsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
import React, {MouseEvent} from 'react';
import {CoreComponentModel} from "../../../AbstractCoreComponent";
import {DownloadV1HeadingContent} from "./DownloadV1HeadingContent";
import {DownloadV1Properties} from "./DownloadV1Properties";
import {EditorPlaceHolder} from "../../../common/placeholder";
import {DownloadV1Description} from "./DownloadV1Description";


export interface DownloadV1LabelsModel {
    filename?: string
    filesize?: string;
    fileformat?: string;
}

export interface DownloadV1Model extends CoreComponentModel{
    url?: string
    title: string
    titleType: string
    description?: string
    actionText?: string
    filename?: string
    displaySize?: boolean
    displayFilename?: boolean
    displayFormat?: boolean
    format?: string
    size?: string
    extension?: string

    labels?: DownloadV1LabelsModel;

    handleOnClick?(event: MouseEvent): void
}


export interface DownloadV1ComputedModel extends DownloadV1Model{
    baseCssCls: string
    containerCssCls: string
    handleOnClick(event: MouseEvent): void
    href: string
    filenameLabel: string
    filesizeLabel: string
    fileformatLabel: string
    displayProperties: boolean
}

export function DownloadV1IsEmptyFn(props:DownloadV1Model): boolean{
    return (props.url == null || props.url.length === 0) && props.handleOnClick == null;
}

export function computeDownloadV1Properties(props:DownloadV1Model):DownloadV1ComputedModel{

    const handleOnClick = (event:MouseEvent) => {
        if(props.handleOnClick){
            props.handleOnClick(event);
        }
    };

    const baseCssCls = 'cmp-download';
    const href = (!!props.url && props.url.length > 0) ? props.url : '#';

    const displayFilename:boolean =  props.displayFilename === true && !!props.filename && props.filename.trim().length > 0;
    const displaySize:boolean =  props.displaySize === true && !!props.size  && props.size.trim().length > 0;
    const displayFormat:boolean =  props.displayFormat === true && !!props.format && props.format.trim().length > 0;

    const { filename = 'Filename', filesize = 'Size',  fileformat = 'Format'} = props.labels || {};

    return {
        ...props,
        displayFilename:displayFilename,
        displaySize: displaySize,
        displayFormat: displayFormat,
        displayProperties: displayFilename || displaySize || displayFormat,
        filenameLabel: filename,
        filesizeLabel: filesize,
        fileformatLabel: fileformat,
        baseCssCls: baseCssCls,
        containerCssCls: baseCssCls + ( props.isInEditor  ? ' cq-dd-file' : ''),
        href: href,
        handleOnClick: handleOnClick
    };
}

function DownloadV1(props:DownloadV1Model){

    const computedProps:DownloadV1ComputedModel = computeDownloadV1Properties(props);
    const isEmpty = DownloadV1IsEmptyFn(props);
  
    return (

        <>
            {isEmpty && props.isInEditor && <EditorPlaceHolder componentTitle={"DownloadV1"} />}
            {!isEmpty && (
                <div className={computedProps.containerCssCls}>
                    {!!computedProps.title && <DownloadV1HeadingContent {...computedProps} />}
                    {!!computedProps.description && <DownloadV1Description {...computedProps} />}
                    {computedProps.displayProperties && <DownloadV1Properties {...computedProps} />}
                    <a onClick={computedProps.handleOnClick} className={computedProps.baseCssCls + '__action'} href={computedProps.href}>
                        <span className={computedProps.baseCssCls + '__action-text'}>{props.actionText}</span>
                    </a>
                </div>
            )}
        </>
    )
};

DownloadV1.defaultProps = {
    isInEditor: false,
    hidePlaceHolder: false,
    titleType: 'h3',
    displaySize: false,
    displayFormat: false,
    displayFilename: false,
    labels: {}
};

export {DownloadV1}

// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/authoring/download/v1/download.v1.component.ts
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ~ Copyright 2020 Adobe Systems Incorporated
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~     http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

import {Component, Input, Output, EventEmitter, HostBinding} from '@angular/core';
import {AbstractCoreComponent} from "../../../AbstractCoreComponent";

export interface DownloadV1LabelsModel {
    filename?: string
    filesize?: string;
    fileformat?: string;
}

export interface DownloadV1Model{
    url?: string
    title: string
    description?: string
    actionText?: string
    filename?: string
    format?: string
    size?: string
    extension: string
    displayFilename: boolean
    displaySize: boolean
    displayFormat: boolean
    labels: DownloadV1LabelsModel
}

@Component({
    selector: 'core-download-v1',
    templateUrl: './download.v1.component.html',
})
export class DownloadV1Component extends AbstractCoreComponent implements DownloadV1Model{

    @HostBinding('class') class = 'cmp-download';

    @Input() titleType = 'h3';
    @Input() text?;
    @Input() url?;
    @Input() title;
    @Input() description?;
    @Input() actionText?;
    @Input() filename?;
    @Input() format?;
    @Input() size?;
    @Input() extension;

    @Input() displayFilename = false;
    @Input() displaySize = false;
    @Input() displayFormat = false;
    @Input() labels: DownloadV1LabelsModel = {
        filename: "File name",
        filesize: "Size",
        fileformat: "Format"
    };

    clickRequest = new EventEmitter();

    onClick() {
        this.clickRequest.emit();
    }

    get containerCssClass():string {
        return this.class + (this.isInEditor) ? ' cq-dd-file' : ''
    }

    get isDisplayingDescription(): boolean{
        return this.description !== null && this.description.trim().length > 0;
    }
    get isDisplayingProperties(): boolean{
        return this.isDisplayingFileformat || this.isDisplayingFilename || this.isDisplayingFilesize;
    }

    get isDisplayingFilesize(): boolean {
        return this.displaySize === true && this.displaySize != null && this.size.trim().length > 0;
    }

    get isDisplayingFileformat(): boolean {
        return this.displayFormat === true && this.format != null && this.format.trim().length > 0;
    }

    get isDisplayingFilename(): boolean {
        return this.displayFilename === true && this.filename != null && this.filename.trim().length > 0;
    }

    get isDisplayingDownloadButton(): boolean {
        return (!!this.url && this.url.trim().length > 0) &&  this.url && (!!this.actionText && this.actionText.trim().length > 0);
    }

    get isEmpty(): boolean {
        return DownloadV1IsEmptyFn(this);
    }

}

export function DownloadV1IsEmptyFn(props:DownloadV1Model): boolean{
    return props.url == null || props.url.trim().length === 0;
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="ButtonV1"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    <div class="{{containerCssClass}}">
        <div [ngSwitch]="titleType">
            <h1 *ngSwitchCase="'h1'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h1>
            <h2 *ngSwitchCase="'h2'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h2>
            <h4 *ngSwitchCase="'h4'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h4>
            <h5 *ngSwitchCase="'h5'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h5>
            <h6 *ngSwitchCase="'h6'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h6>
            <h3 *ngSwitchDefault  class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h3>
        </div>
       
        <div class="{{class}}__description" *ngIf="isDisplayingDescription" [innerHTML]="description | safeHtml"></div>
        <dl *ngIf="isDisplayingProperties" class="{{class}}__properties">
            <div *ngIf="isDisplayingFilename" class="{{class}}__property {{class}}__property--filename">
                <dt class="{{class}}__property-label">{{labels.filename}}</dt>
                <dd class="{{class}}__property-content">{{filename}}</dd>
            </div>
            <div *ngIf="isDisplayingFilesize" class="{{class}}__property {{class}}__property--size">
                <dt class="{{class}}__property-label">{{labels.filesize}}</dt>
                <dd class="{{class}}__property-content">{{size}}</dd>
            </div>
            <div *ngIf="isDisplayingFileformat" class="{{class}}__property {{class}}__property--format">
                <dt class="{{class}}__property-label">{{labels.fileformat}}</dt>
                <dd class="{{class}}__property-content">{{format}}</dd>
            </div>
        </dl>
        
        <a *ngIf="isDisplayingDownloadButton" class="{{class}}__action" href="{{url}}">
            <span class="{{class}}__action-text">{{actionText}}</span>
        </a>
    </div>
</ng-template>
