// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/authoring/button/v1/button.v1.component.ts
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ~ Copyright 2020 Adobe Systems Incorporated
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~     http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

import {Component, EventEmitter, HostBinding, Input} from '@angular/core';
import {AbstractRoutedCoreComponent} from "../../../AbstractRoutedCoreComponent";
import {RoutedCoreComponentModel} from "../../../model/RoutedCoreComponentModel";

export interface ButtonV1Model extends RoutedCoreComponentModel{
    text?: string;
    link?: string;
    icon?: string;
    ariaLabel?: string;
}

@Component({
    selector: 'core-button-v1',
    templateUrl: './button.v1.component.html',
})
export class ButtonV1Component extends AbstractRoutedCoreComponent implements ButtonV1Model{

    @HostBinding('class') class = 'cmp-button';
    @Input() text?;
    @Input() link?;
    @Input() icon?;
    @Input() ariaLabel?;

    clickRequest = new EventEmitter();

    get iconClass():string{
        return `${this.class}__icon __icon--${this.icon}`;
    }

    onClick() {
        this.clickRequest.emit();
    }

    get isEmpty(): boolean {
        return ButtonV1IsEmptyFn(this);
    }
}

export function ButtonV1IsEmptyFn(props:ButtonV1Model): boolean{
    return props.text == null || props.text.trim().length === 0;
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="ButtonV1"></core-placeholder>
</ng-template>
<ng-template #componentBlock>
    <div *ngIf="link; then linkBlock else staticBlock"></div>
</ng-template>

<ng-template #linkBlock>
    <ng-container *ngIf="routed">
        <ng-container *ngTemplateOutlet="routedLink"></ng-container>
    </ng-container>
    <ng-container *ngIf="!routed">
        <ng-container *ngTemplateOutlet="staticLink"></ng-container>
    </ng-container>
</ng-template>
<ng-template #staticBlock>
    <button (click)="onClick()">
        <span *ngIf="icon" class="{{iconClass}}"></span>
        <span class="{{class}}__text" [innerText]="text"></span>
    </button>
</ng-template>

<ng-template #routedLink>
    <a routerLink="{{link}}"
       routerLinkActive="active"
       (click)="onClick()">
        <span *ngIf="icon" class="{{iconClass}}"></span>
        <span class="{{class}}__text" [innerText]="text"></span>
    </a>
</ng-template>

<ng-template #staticLink>
    <a [href]="link" (click)="onClick()">
        <span *ngIf="icon" class="{{iconClass}}"></span>
        <span class="{{class}}__text" [innerText]="text"></span>
    </a>
</ng-template>

// react/react-core/src/core/authoring/button/v1/ButtonV1.tsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import React, {MouseEvent} from 'react';
import {CoreComponentModel, CoreComponentState,AbstractCoreComponent} from "../../../AbstractCoreComponent";

export interface ButtonV1Model extends CoreComponentModel{
    text?: string;
    link?: string;
    icon?: string;
    ariaLabel?: string;
    handleOnClick?(event: MouseEvent): void
}

export function ButtonV1IsEmptyFn(props:ButtonV1Model): boolean{
    return props.text == null || props.text.length === 0;
}

export class ButtonV1<Model extends ButtonV1Model, State extends CoreComponentState> extends AbstractCoreComponent<Model, State> {

    public static defaultProps = {
        isInEditor: false,
        hidePlaceHolder: false
    };

    constructor(props:Model) {
        super(props, "cmp-button", "ButtonV1");
        this.handleOnClick = this.handleOnClick.bind(this);
    }

    handleOnClick(event:MouseEvent){
        if(this.props.handleOnClick){
            this.props.handleOnClick(event);
        }
    }
    getContent(){
        return (
            <>
                { this.props.icon && <span className={`${this.baseCssCls}__icon ${this.baseCssCls}__icon--${this.props.icon}`}></span>  }
                <span className={this.baseCssCls + '__text'}>{this.props.text}</span>
            </>
        );
    }

    isEmpty(): boolean{
        return ButtonV1IsEmptyFn(this.props);
    }

    renderComponent(){

        const isLink =  (!!this.props.link);
        const type = isLink ? 'a' : 'button';
        let props = this.generateAttributes(isLink);

        return  (
           React.createElement(
                type,
                props,
                this.getContent()
           )
        )
    }

    generateAttributes(isLink: boolean) {
        let props: any = {
            className: this.baseCssCls,
            onClick: this.handleOnClick
        };

        if (isLink) {
            props['aria-label'] = this.props.ariaLabel;
            props['href'] = this.props.link;
        }
        return props;
    }
};
