// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/authoring/teaser/v1/teaser.v1.component.ts
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import {Component, HostBinding, Input} from "@angular/core";
import {AbstractRoutedCoreComponent} from "../../../AbstractRoutedCoreComponent";

export function TeaserV1IsEmptyFn(props:TeaserV1Model): boolean{
    return (!props.imagePath && !props.description &&  props.actions.length == 0)
}

export interface TeaserV1Action {
    title: string
    URL: string
    routed?: boolean
}

export interface TeaserV1Model{
    pretitle?: string
    title?: string
    description?: string
    titleType: string
    linkURL: string
    actionsEnabled: boolean
    imageLinkHidden: boolean
    titleLinkHidden: boolean
    actions: TeaserV1Action[]
    imagePath: string
}


@Component({
    selector: 'core-teaser-v1',
    templateUrl: './teaser.v1.component.html',
})
export class TeaserV1Component extends AbstractRoutedCoreComponent implements TeaserV1Model{

    @HostBinding('class') class = 'cmp-teaser';

    @Input() pretitle?: string;
    @Input() title?: string;
    @Input() description?: string;
    @Input() titleType: string;
    @Input() linkURL: string;
    @Input() actionsEnabled: boolean = false;
    @Input() imageLinkHidden: boolean;
    @Input() titleLinkHidden: boolean;
    @Input() actions: TeaserV1Action[];
    @Input() imagePath: string;

    get isEmpty(): boolean {
        return TeaserV1IsEmptyFn(this);
    }
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="TeaserV1"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    
    <div class="{{class}}__image">
        <div class="{{class}}">
            <core-image-v2 [src]="imagePath" [title]="title"></core-image-v2>
        </div>
    </div>
    <div class="{{class}}__content">
        <div *ngIf="pretitle" class="{{class}}__pretitle">{{pretitle}}</div>
        <core-title-v2 [routed]="routed" [linkURL]="linkURL" [text]="title" [type]="titleType"></core-title-v2>
        <div *ngIf="description" class="{{class}}__description" [innerHTML]="description | safeHtml"></div>
        <div *ngIf="actionsEnabled" class="{{class}}__action-container">
            <a *ngFor="let action of actions"  class="{{class}}__action-link" href="{{action.URL}}">{{action.title}}</a>
        </div>
        
    </div>

</ng-template>

// react/react-core/src/core/authoring/teaser/v1/TeaserV1.tsx
import React from "react";
import {AbstractCoreComponent, CoreComponentModel, CoreComponentState} from "../../../AbstractCoreComponent";
import {ImageV2} from "../../../../core/authoring/image/v2/ImageV2";
import {TitleV2} from "../../../../core/authoring/title/v2/TitleV2";

export function TeaserV1IsEmptyFn(props:TeaserV1Model): boolean{

    return (!props.imagePath && !props.description &&  props.actions.length == 0)

}

export interface TeaserV1Action {
    title: string
    URL: string;
}

export interface TeaserV1Model extends CoreComponentModel{
    pretitle?: string
    title?: string
    description?: string
    titleType: string
    linkURL: string
    actionsEnabled: boolean
    imageLinkHidden: boolean
    titleLinkHidden: boolean
    actions: TeaserV1Action[]
    imagePath: string
}

export class TeaserV1<Model extends TeaserV1Model, State extends CoreComponentState> extends AbstractCoreComponent<Model, State>{

    public static defaultProps = {
        hidePlaceHolder: false,
        isInEditor: false
    };

    constructor(props: Model) {
        super(props, 'cmp-teaser', 'TeaserV1');
    }

    isEmpty(): boolean {
        return TeaserV1IsEmptyFn(this.props);
    }

    get image(){
        return this.props.imagePath && (
            <div className={this.baseCssCls + '__image'}>
                <ImageV2 isInEditor={this.props.isInEditor} src={this.props.imagePath} alt={"temporary image"}/>
            </div>
        );
    }

    get pretitle(){
        return this.props.pretitle && <div className={this.baseCssCls + '__pretitle'}>{this.props.pretitle}</div>

    }

    get title(){
        return this.props.title && (
            <TitleV2 type={this.props.titleType}
                     isInEditor={this.props.isInEditor}
                     linkDisabled={false}
                     text={this.props.title}
                     linkURL={this.props.linkURL}/>
            )
    }

    get description(){
        const text:string = this.props.description as string;
        return this.props.description && (
           <div className={this.baseCssCls + '__description'} dangerouslySetInnerHTML={{__html: text}}></div>
        )
    }

    generateLink(action:TeaserV1Action, index:number){
        return (
            <a className={this.baseCssCls + '__action-link'} href={action.URL}>${action.title}</a>
        )
    }

    get actions(){
        const hasActions:boolean = this.props.actions.length > 0;
        return this.props.actionsEnabled && hasActions && (
            <div className={this.baseCssCls + '__action-container'}>
                {
                    this.props.actions.map((action, index) => {
                        this.generateLink(action,index)
                    })
                }
            </div>
        )
    }

    renderComponent(): JSX.Element {

        const cssClass = this.baseCssCls + (this.props.isInEditor) ? ' cq-dd-image' : '';
        return (
            <div className={cssClass}>
                {this.image}
                <div className={this.baseCssCls + '__content'}>
                    {this.pretitle}
                    {this.title}
                    {this.description}
                    {this.actions}
                </div>
            </div>
        )
    }

}
