// react/react-core/src/core/breadcrumb/v2/BreadCrumbV2.tsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import React from 'react';
import {CoreComponent} from "../../../types";
import AbstractCoreComponent from "../../AbstractCoreComponent";

export interface BreadCrumbV2ItemModel {
    active: boolean
    url: string
    title: string
}

export interface BreadCrumbV2Model extends CoreComponent {
    items: BreadCrumbV2ItemModel[]
    ariaLabelI18n: string
}


export function BreadCrumbV2IsEmptyFn(props:BreadCrumbV2Model): boolean{
    return props.items == null || props.items.length === 0;
}

export class BreadCrumbV2<Model extends BreadCrumbV2Model> extends AbstractCoreComponent<Model, any> {

    public static defaultProps = {
        ariaLabelI18n: "BreadCrumbV2",
        hidePlaceHolder: false
    };

    isEmpty(): boolean {
        return BreadCrumbV2IsEmptyFn(this.props)
    }

    getEmptyPlaceHolderText(): string {
        return 'BreadCrumbV2';
    }

    renderBreadCrumbListItem(crumbItem:BreadCrumbV2ItemModel,index:number): JSX.Element{

        const className = 'cmp-breadcrumb__item' + (crumbItem.active ? ' cmp-breadcrumb__item--active' : '');
        const contentIndex:string = index.toString(2);

        return (
            <li className={className}
                key={'crumbitem-' + index}
                itemProp="itemListElement" itemScope itemType="http://schema.org/ListItem">
                {
                    !crumbItem.active && this.renderBreadCrumbLink(crumbItem,index)
                }
                {
                    crumbItem.active && this.renderBreadCrumbSpan(crumbItem,index)
                }
                <meta itemProp="position" content={contentIndex}/>
            </li>
        );
    }

    renderBreadCrumbLink(crumbItem:BreadCrumbV2ItemModel,index:number){
        return (
            <a href={crumbItem.url}
                      className="cmp-breadcrumb__item-link"
                      itemProp="item">
                {this.renderBreadCrumbSpan(crumbItem, index)}
            </a>
        )
    }

    renderBreadCrumbSpan(crumbItem:BreadCrumbV2ItemModel,index:number){
        return <span itemProp="name">{crumbItem.title}</span>
    }

    renderComponent(){
        return (
            <nav className="cmp-breadcrumb"
                 aria-label={this.props.ariaLabelI18n}>
                <ol className="cmp-breadcrumb__list"
                    itemScope itemType="http://schema.org/BreadcrumbList">
                    {this.props.items.map((item, index) => {
                        return this.renderBreadCrumbListItem(item, index)
                    })}
                </ol>
            </nav>
        )
    }

}

// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/layout/breadcrumb/v2/breadcrumb.v2.component.ts
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import {Component, HostBinding, Inject, Input} from "@angular/core";
import {AbstractRoutedCoreComponent} from "../../../AbstractRoutedCoreComponent";
import {NAVIGATION_UTIL_SERVICE, NavigationUtilityService} from "../../../services/NavigationUtilityService";
import {NavigationItemModel} from "../../../model/NavigationItemModel";
import {RoutedCoreComponentModel} from "../../../model/RoutedCoreComponentModel";

export interface BreadCrumbV2ItemModel extends NavigationItemModel{
    active: boolean
    url: string
    title: string
}

export interface BreadCrumbV2Model extends RoutedCoreComponentModel{
    items: BreadCrumbV2ItemModel[]
    ariaLabelI18n: string
}

export function BreadCrumbV2IsEmptyFn(props: BreadCrumbV2Model): boolean {
    return props.items == null || props.items.length === 0;
}

@Component({
    selector: 'core-breadcrumb-v2',
    templateUrl: './breadcrumb.v2.component.html'
})
export class BreadCrumbV2Component extends AbstractRoutedCoreComponent implements BreadCrumbV2Model {

    @HostBinding('class') class = 'cmp-breadcrumb';
    navigationUtilService: NavigationUtilityService;

    @Input() items;
    @Input() ariaLabelI18n;

    constructor(@Inject(NAVIGATION_UTIL_SERVICE) navigationUtilService: NavigationUtilityService) {
        super();
        this.navigationUtilService = navigationUtilService;
    }

    get isEmpty(): boolean {
        return BreadCrumbV2IsEmptyFn(this);
    }

    getItemCssClass(item: BreadCrumbV2ItemModel): string {
        return this.navigationUtilService.isItemActive(item) ? this.class + '__item ' + this.class + '__item--active' : this.class + '__item';
    }


}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="BreadCrumbV2"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    <nav class="{{class}}"
         [attr.aria-label]="ariaLabelI18n">
        <ol class="{{class}}__list">
            <ng-container *ngFor="let item of items; let i = index">
                <li [ngClass]="getItemCssClass(item)">
    
                    <ng-container *ngIf="isItemRouted(item) && !item.active" [ngTemplateOutlet]="routedLink" [ngTemplateOutletContext]="{item:item}"></ng-container>
                    <ng-container *ngIf="!isItemRouted(item) && !item.active" [ngTemplateOutlet]="staticLink" [ngTemplateOutletContext]="{item:item}"></ng-container>
                    <ng-container *ngIf="item.active" [ngTemplateOutlet]="title" [ngTemplateOutletContext]="{item:item}"></ng-container>
                    
                    <span *ngIf="item.active" itemProp="name">{{item.title}}</span>
                    <meta itemProp="position" content="{{i}}"/>
                </li>
            </ng-container>
        </ol>
    </nav>
</ng-template>

<ng-template #routedLink let-item='item'>
    <a class="{{class}}__item-link"
       routerLink="{{ item.url }}"
       routerLinkActive="active">
        <ng-container [ngTemplateOutlet]="title" [ngTemplateOutletContext]="{item:item}"></ng-container>
    </a>
</ng-template>


<ng-template #staticLink let-item='item'>
    <a class="{{class}}__item-link"
       href="{{item.url}}">
        <ng-container [ngTemplateOutlet]="title" [ngTemplateOutletContext]="{item:item}"></ng-container>
    </a>
</ng-template>


<ng-template #title let-item='item'>
    <span itemProp="name">{{item.title}}</span>
</ng-template>
