// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/authoring/download/v1/download.v1.component.ts
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ~ Copyright 2020 Adobe Systems Incorporated
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~     http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

import {Component, Input, Output, EventEmitter, HostBinding} from '@angular/core';
import {AbstractCoreComponent} from "../../../AbstractCoreComponent";

export interface DownloadV1LabelsModel {
    filename?: string
    filesize?: string;
    fileformat?: string;
}

export interface DownloadV1Model{
    url?: string
    title: string
    description?: string
    actionText?: string
    filename?: string
    format?: string
    size?: string
    extension: string
    displayFilename: boolean
    displaySize: boolean
    displayFormat: boolean
    labels: DownloadV1LabelsModel
}

@Component({
    selector: 'core-download-v1',
    templateUrl: './download.v1.component.html',
})
export class DownloadV1Component extends AbstractCoreComponent implements DownloadV1Model{

    @HostBinding('class') class = 'cmp-download';

    @Input() titleType = 'h3';
    @Input() text?;
    @Input() url?;
    @Input() title;
    @Input() description?;
    @Input() actionText?;
    @Input() filename?;
    @Input() format?;
    @Input() size?;
    @Input() extension;

    @Input() displayFilename = false;
    @Input() displaySize = false;
    @Input() displayFormat = false;
    @Input() labels: DownloadV1LabelsModel = {
        filename: "File name",
        filesize: "Size",
        fileformat: "Format"
    };

    clickRequest = new EventEmitter();

    onClick() {
        this.clickRequest.emit();
    }

    get containerCssClass():string {
        return this.class + (this.isInEditor) ? ' cq-dd-file' : ''
    }

    get isDisplayingDescription(): boolean{
        return this.description !== null && this.description.trim().length > 0;
    }
    get isDisplayingProperties(): boolean{
        return this.isDisplayingFileformat || this.isDisplayingFilename || this.isDisplayingFilesize;
    }

    get isDisplayingFilesize(): boolean {
        return this.displaySize === true && this.displaySize != null && this.size.trim().length > 0;
    }

    get isDisplayingFileformat(): boolean {
        return this.displayFormat === true && this.format != null && this.format.trim().length > 0;
    }

    get isDisplayingFilename(): boolean {
        return this.displayFilename === true && this.filename != null && this.filename.trim().length > 0;
    }

    get isDisplayingDownloadButton(): boolean {
        return (!!this.url && this.url.trim().length > 0) &&  this.url && (!!this.actionText && this.actionText.trim().length > 0);
    }

    get isEmpty(): boolean {
        return DownloadV1IsEmptyFn(this);
    }

}

export function DownloadV1IsEmptyFn(props:DownloadV1Model): boolean{
    return props.url == null || props.url.trim().length === 0;
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="ButtonV1"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    <div class="{{containerCssClass}}">
        <div [ngSwitch]="titleType">
            <h1 *ngSwitchCase="'h1'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h1>
            <h2 *ngSwitchCase="'h2'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h2>
            <h4 *ngSwitchCase="'h4'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h4>
            <h5 *ngSwitchCase="'h5'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h5>
            <h6 *ngSwitchCase="'h6'" class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h6>
            <h3 *ngSwitchDefault  class="{{class}}__title">
                <a *ngIf="url" class="{{class}}__title-link" [href]="url">{{title}}</a>
            </h3>
        </div>
       
        <div class="{{class}}__description" *ngIf="isDisplayingDescription" [innerHTML]="description | safeHtml"></div>
        <dl *ngIf="isDisplayingProperties" class="{{class}}__properties">
            <div *ngIf="isDisplayingFilename" class="{{class}}__property {{class}}__property--filename">
                <dt class="{{class}}__property-label">{{labels.filename}}</dt>
                <dd class="{{class}}__property-content">{{filename}}</dd>
            </div>
            <div *ngIf="isDisplayingFilesize" class="{{class}}__property {{class}}__property--size">
                <dt class="{{class}}__property-label">{{labels.filesize}}</dt>
                <dd class="{{class}}__property-content">{{size}}</dd>
            </div>
            <div *ngIf="isDisplayingFileformat" class="{{class}}__property {{class}}__property--format">
                <dt class="{{class}}__property-label">{{labels.fileformat}}</dt>
                <dd class="{{class}}__property-content">{{format}}</dd>
            </div>
        </dl>
        
        <a *ngIf="isDisplayingDownloadButton" class="{{class}}__action" href="{{url}}">
            <span class="{{class}}__action-text">{{actionText}}</span>
        </a>
    </div>
</ng-template>

// react/react-core/src/core/download/v1/DownloadV1.tsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
import React, {MouseEvent} from 'react';
import {CoreComponentModel, CoreComponentState} from "../../../types";
import AbstractCoreComponent from "../../AbstractCoreComponent";

export interface DownloadV1Model extends CoreComponentModel{
    url?: string
    title: string
    titleType: string
    description?: string
    actionText?: string
    filename?: string
    displaySize: boolean
    displayFilename: boolean
    displayFormat: boolean
    format?: string
    size?: string
    extension?: string
    handleOnClick?(event: MouseEvent): void
}

export function DownloadV1IsEmptyFn(props:DownloadV1Model): boolean{
    return (props.url == null || props.url.length === 0) && props.handleOnClick == null;
}

export class DownloadV1<Model extends DownloadV1Model, State extends CoreComponentState> extends AbstractCoreComponent<Model, State> {

    displayFileName:boolean;
    displaySize: boolean;
    displayFormat: boolean;

    public static defaultProps = {
        isInEditor: false,
        hidePlaceHolder: false,
        titleType: 'h3',
        displaySize: false,
        displayFormat: false,
        displayFilename: false
    };

    constructor(props:Model) {
        super(props);
        this.handleOnClick = this.handleOnClick.bind(this);
        this.displayFileName = props.displayFilename && !!props.filename;
        this.displaySize = props.displaySize && !!props.size;
        this.displayFormat = props.displayFormat && !!props.format;
        this.handleOnClick = this.handleOnClick.bind(this);
    }

    getEmptyPlaceHolderText(): string {
        return 'Contrib Download V1';
    }

    handleOnClick(event:MouseEvent){
        if(this.props.handleOnClick){
            this.props.handleOnClick(event);
        }
    }

    isEmpty(): boolean{
        return DownloadV1IsEmptyFn(this.props);
    }

    renderHeadingContent(){
        return (
            <>
                {!!this.props.url || !!this.props.handleOnClick && (
                    <a onClick={this.handleOnClick}
                       className="cmp-download__title-link"
                       href={this.getHref()}>
                        {this.props.title}
                    </a>
                )}
                {!this.props.url && ( <> {this.props.title} </>)}
            </>
        )
    }

    renderHeading(){
        return (
            React.createElement(
                `${this.props.titleType}`,
                {
                    className: 'cmp-download__title"',
                },
                this.renderHeadingContent()
            )
        )
    }

    renderDetails(){
        return (
            <dl className="cmp-download__properties">
                {this.displayFileName && this.renderProperty('Filename', this.props.filename, 'filename')}
                {this.displaySize     && this.renderProperty('Size',     this.props.size,     'size')}
                {this.displayFormat   && this.renderProperty('Format',   this.props.format,   'format')}
            </dl>
        )
    }
    renderComponent(){

        const cssClass = 'cmp-download' + ( this.props.isInEditor  ? ' cq-dd-file' : '');
        return (
            <div className={cssClass}>
                {!!this.props.title && this.renderHeading()}
                {!!this.props.description && this.renderDescription()}
                {(this.displayFileName || this.displaySize || this.displayFormat) && this.renderDetails()}
                {this.renderDownloadLink()}

            </div>
        )
    }

    renderDescription() {
        const html:string = String(this.props.description) || '';
        return (
            <div className="cmp-download__description" dangerouslySetInnerHTML={{__html: html}}></div>
        )
    }

    renderDownloadLink() {


        return (
            <a onClick={this.handleOnClick} className="cmp-download__action" href={this.getHref()}>
                <span className="cmp-download__action-text">{this.props.actionText}</span>
            </a>
        )
    }

    renderProperty(label: string, content: string|undefined, cssClassModifier: string) {
        const cssClass = 'cmp-download__property cmp-download__property--' + cssClassModifier;
        return (
            <div className={cssClass}>
                <dt className="cmp-download__property-label">{label}</dt>
                <dd className="cmp-download__property-content">{content}</dd>
            </div>
        );
    }

    getHref(){
        return (!!this.props.url && this.props.url.length > 0) ? this.props.url : '#';
    }
}
