// angular/angular-core/projects/aem-angular-core-wcm-components/src/lib/authoring/title/v2/title.v2.component.ts
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import {Component, HostBinding, Input} from "@angular/core";
import {AbstractRoutedCoreComponent} from "../../../AbstractRoutedCoreComponent";

export interface TitleV2Model{
    text?: string;
    linkURL?: string;
    linkDisabled: boolean;
    type: string;
}

export function TitleV2IsEmptyFn(props:TitleV2Model): boolean{
    return props.text == null || props.text.trim().length === 0;
}

@Component({
    selector: 'core-title-v2',
    templateUrl: './title.v2.component.html',
})
export class TitleV2 extends AbstractRoutedCoreComponent implements TitleV2Model{

    @HostBinding('class') @Input()  class = 'cmp-title';

    @Input() text?;
    @Input() linkURL?;
    @Input() linkDisabled = false;
    @Input() type = 'h3';

    get isEmpty(): boolean {
        return TitleV2IsEmptyFn(this);
    }

    get hasLink(): boolean{
        return !!this.linkURL && this.linkURL.trim().length > 0;
    }
}
<div *ngIf="isEmpty; then placeHolderBlock else componentBlock"></div>

<ng-template #placeHolderBlock>
    <core-placeholder componentTitle="TitleV2"></core-placeholder>
</ng-template>

<ng-template #componentBlock>
    <div *ngIf="hasLink; else heading">
        <a *ngIf="routed" class="{{class}}__item-link"
           routerLink="{{ linkURL}}"
           routerLinkActive="active">
            <ng-container *ngTemplateOutlet="heading"></ng-container>
        </a>
        <a *ngIf="!routed" href="{{linkURL}}">
            <ng-container *ngTemplateOutlet="heading"></ng-container>
        </a>
    </div>
</ng-template>

<ng-template #heading>
    <div [ngSwitch]="type">
        <h1 class="{{class}}__text" *ngSwitchCase="'h1'">{{text}}</h1>
        <h2 class="{{class}}__text" *ngSwitchCase="'h2'">{{text}}</h2>
        <h4 class="{{class}}__text" *ngSwitchCase="'h4'">{{text}}</h4>
        <h5 class="{{class}}__text" *ngSwitchCase="'h5'">{{text}}</h5>
        <h6 class="{{class}}__text" *ngSwitchCase="'h6'">{{text}}</h6>
        <h3 class="{{class}}__text" *ngSwitchDefault>{{text}}</h3>
    </div>
</ng-template>

// react/react-core/src/core/title/v2/TitleV2.tsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import React from 'react';
import {CoreComponent} from "../../../types";
import AbstractCoreComponent from "../../AbstractCoreComponent";

export interface TitleV2Model extends CoreComponent{
    text?: string;
    linkURL?: string;
    linkDisabled: boolean;
    type: string;
}

export function TitleV2IsEmptyFn(props:TitleV2Model): boolean{
    return props.text == null || props.text.length === 0;
}

export class TitleV2<Model extends TitleV2Model> extends AbstractCoreComponent<Model, any> {

    public static defaultProps = {
        hidePlaceHolder: false
    };

    getEmptyPlaceHolderText(): string {
        return 'Contrib Title V2';
    }


    isEmpty(): boolean{
        return TitleV2IsEmptyFn(this.props);
    }

    getContents(){

        if( !this.props.linkDisabled){
            return (
                <a className="cmp-title__link" href={this.props.linkURL ? this.props.linkURL : '#'}>
                    {this.props.text}
                </a>
            )
        }

        return (
            <>
                {this.props.text}
            </>
        )
    }

    renderComponent(){

        return (
            <div className="cmp-title">
                {
                    React.createElement(
                        `${this.props.type}`,
                        {
                            className: 'cmp-title__text',
                        },
                        this.getContents()
                    )
                }

            </div>
        )
    }
}
