// react/react-core-spa/src/core/container/carousel/v1/CarouselV1.jsx
/*
 *  Copyright 2020 Adobe
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import React from 'react';

import {AbstractCoreContainerComponent} from "../../../AbstractCoreContainerComponent";
import {ComponentMapping} from '@adobe/cq-react-editable-components';
import {sprintf} from 'sprintf';

export function CarouselV1IsEmptyFn(props){
    return props.cqItems == null || props.cqItems.length === 0;
}

export class CarouselV1 extends AbstractCoreContainerComponent {

    constructor(props) {
        super(props,"cmp-carousel");

        this.state = {
            activeIndex: 0,
            isMouseEntered: false,
            autoPlay: this.props.autoplay,
            componentMapping: this.props.componentMapping || ComponentMapping
        };

        this.handleIndicatorClick = this.handleIndicatorClick.bind(this);
        this.handleOnButtonPrev   = this.handleOnButtonPrev.bind(this);
        this.handleOnButtonNext   = this.handleOnButtonNext.bind(this);
        this.handleOnMouseEnter   = this.handleOnMouseEnter.bind(this);
        this.handleOnMouseLeave   = this.handleOnMouseLeave.bind(this);

        if( this.props.autoplay && !this.props.isInEditor){
            this.autoPlay();
        }

    }

    handleOnButtonPrev(){
        this.prevSlide();
    }

    handleOnButtonNext(){
        this.nextSlide();
    }

    handleOnMouseEnter(){
        if(!this.props.autopauseDisabled && this.props.autoplay){
            this.clearAutoPlay();
        }
    }

    handleOnMouseLeave(){
        if(!this.props.autopauseDisabled && this.props.autoplay){
            this.autoPlay();
        }
    }

    handleOnButtonPrev(){
        this.prevSlide();
    }

    handleOnButtonNext(){
        this.nextSlide();
    }


    handleIndicatorClick(index){

        if(this.state.activeIndex !== index){

            this.setState({
                activeIndex: index
            });
        }
    }

    autoPlay(){
        this.interval = setInterval(() => {
            this.autoPlayTick();
        }, this.props.delay);
    }

    autoPlayTick() {

        if (!this.state.autoPlay || this.props.cqItemsOrder.length <= 1) {
            return;
        }

        this.nextSlide();
    };

    clearAutoPlay(){
        clearInterval(this.interval);
    };

    toggleAutoPlay(toggle){
        this.setState({
            autoPlay: toggle
        })
    }

    nextSlide(){

        const activeIndex = this.__getActiveIndex();

        if(activeIndex=== (this.props.cqItemsOrder.length-1)){

            this.__setSlide(0);
        }else{
            this.__setSlide(activeIndex + 1);
        }
    }

    prevSlide(){
        const activeIndex = this.__getActiveIndex();
        if(activeIndex === 0){

            this.__setSlide(this.props.cqItemsOrder.length - 1);
        }else{
            this.__setSlide(activeIndex - 1);
        }
    }

    __getActiveIndex(){

        return this.state.activeIndex;
    }

    __setSlide(index){

        this.setState({
            activeIndex: index
        });
    }



    render() {

        const isEmpty = CarouselV1IsEmptyFn(this.props);
        return (
            <div className={this.baseCssCls}
                 role="group"
                 aria-label={this.props.accessibilityLabel}
                 aria-roledescription="carousel">
                {
                    !isEmpty && this.renderCarousel()
                }
                { this.placeholderComponent }
            </div>
        )

    }

    displayItem(item, index){

        const isActive = index === this.state.activeIndex;
        //we display the item if active is true, or if we are in the author mode. we need to always display the item for the author mode to work properly.
        const display = !!(isActive || this.props.isInEditor);

        const cssClass = isActive ? `${this.baseCssCls}__item ${this.baseCssCls}__item--active` : `${this.baseCssCls}__item`;
        const ariaLabel = sprintf(this.props.accessibility.slide, (index + 1), this.props.cqItemsOrder.length);

        return (
            <div key={'item-' + index}
                       className={cssClass}
                       role="tabpanel"
                       aria-label={ariaLabel}
                       data-cmp-hook-carousel="item">
                {display && item}
            </div>
        )
    }

    renderCarousel(){
        return (

            <div className={this.baseCssCls + '__content'} onMouseEnter={()=>this.handleOnMouseEnter()} onMouseLeave={()=>this.handleOnMouseLeave()} >
                {
                    this.childComponents.map((childComponent, index) => this.displayItem(childComponent,index))
                }
                {this.renderCarouselActions()}
                {this.renderCarouselIndicators()}
            </div>
        )
    }

    renderCarouselIndicators(){
        return (
            <ol className={this.baseCssCls + '__indicators'}
                role="tablist"
                aria-label={this.props.accessibility.indicators}>
                {

                    this.props.cqItemsOrder.map((key, index) => {

                        const item = this.props.cqItems[key];

                        const cssClass = (index === this.state.activeIndex) ? `${this.baseCssCls}__indicator ${this.baseCssCls}__indicator--active` : `${this.baseCssCls}__indicator`;
                        const ariaLabelItem = sprintf(this.props.accessibility.indicator, (index + 1));
                        return (
                            <li
                                key={'item-' + index}
                                onClick={()=>this.handleIndicatorClick(index)}
                                className={cssClass}
                                role="tab"
                                aria-label={ariaLabelItem}>{item.title}</li>
                        )
                    })
                }

            </ol>
        );
    }
    renderCarouselActions(){
        return (
            <div className={this.baseCssCls + '__actions'}>
                <button onClick={()=>this.handleOnButtonPrev()}
                        className={`${this.baseCssCls}__action ${this.baseCssCls}__action--previous`}
                        type="button"
                        aria-label={this.props.accessibility.previous}>
                    <span className={this.baseCssCls + '__action-icon'}></span>
                    <span className={this.baseCssCls + '__action-text'}>{this.props.accessibility.previous}</span>
                </button>
                <button onClick={()=>this.handleOnButtonNext()}
                        className={`${this.baseCssCls}__action ${this.baseCssCls}__action--next`}
                        type="button"
                        aria-label={this.props.accessibility.next}>
                    <span className={this.baseCssCls + '__action-icon'}></span>
                    <span className={this.baseCssCls + '__action-text'}>{this.props.accessibility.next}</span>
                </button>
                {
                    this.props.autoplay &&
                    <React.Fragment>
                        <button className={`${this.baseCssCls}__action ${this.baseCssCls}__action--pause ` + (!this.state.autoPlay ? this.baseCssCls + '__action--disabled' : '')}
                                type="button"
                                aria-label={this.props.accessibility.pause}
                                onClick={()=>this.toggleAutoPlay(false)}>
                            <span className={this.baseCssCls + '__action-icon'}></span>
                            <span className={this.baseCssCls + '__action-text'}>{this.props.accessibility.pause}</span>
                        </button>
                        <button className={`${this.baseCssCls}__action ${this.baseCssCls}__action--play ` + (this.state.autoPlay ? this.baseCssCls + '__action--disabled' : '')}
                                type="button"
                                aria-label={this.props.accessibility.play}
                                onClick={()=>this.toggleAutoPlay(true)}
                        >
                            <span className={this.baseCssCls + '__action-icon'}></span>
                            <span className={this.baseCssCls + '__action-text'}>{this.props.accessibility.play}</span>
                        </button>
                    </React.Fragment>
                }

            </div>
        )
    }

}

CarouselV1.defaultProps = {
    isInEditor: false,
    autoplay: false,
    cqItems: {},
    cqItemsOrder: [],
    accessibilityLabel: 'Carousel',
    accessibility: {
        play: 'Play',
        pause: 'Pause',
        next: 'Next',
        previous: 'Previous',
        slide: 'Slide %1$u of %2$u',
        indicator: 'Slide %1$u',
        indicators: 'Choose a slide to display'
    }
};

// angular/angular-core/projects/aem-angular-core-spa-wcm-components/src/lib/containers/carousel/v1/carousel.v1.component.ts
import {ContainerProperties} from "../../../common";
import {Component, HostBinding, Input, OnInit} from "@angular/core";
import {AbstractContainerComponent} from "../../AbstractContainerComponent";

export interface CarouselV1PropertiesAccessibility {
    play: string;
    pause: string;
    next: string;
    previous: string;
    slide: string;
    indicator: string;
    indicators:string;
}

const formatFn = (value:string, args:any[]) => {
    var content = value;
    for (var i = 0; i < args.length; i++) {
        var replacement = '{' + i + '}';
        content = content.replace(replacement, args[i]);
    }
    return content;
};

export interface CarouselV1Properties extends ContainerProperties{
    id:string;
    autopauseDisabled:boolean
    accessibility:CarouselV1PropertiesAccessibility
}

@Component({
    selector: 'core-carousel-v1',
    host: {
        '[class]': 'hostClasses',
        '[attr.data-cq-data-path]':'cqPath'
    },
    templateUrl: './carousel.v1.component.html'
})
export class CarouselV1Component extends AbstractContainerComponent implements CarouselV1Properties,OnInit{

    @Input() id = "carousel";
    @Input() autoplay: false;
    @Input() accessibilityLabel = 'Carousel';
    @Input() autopauseDisabled: false;
    @Input() activeIndex: number = 0;
    @Input() delay: number = 0;
    @HostBinding('class') class = 'cmp-carousel';


    @Input() accessibility = {
        play: 'Play',
        pause: 'Pause',
        next: 'Next',
        previous: 'Previous',
        slide: 'Slide {0} of {1}',
        indicator: 'Slide {0}',
        indicators: 'Choose a slide to display'
    };

    interval;

    ngOnInit(): void {
        if (this.autoplay && !this.isInEditor) {
            this.__autoPlay();
        }
    }

    handleOnMouseEnter(){
        if(!this.autopauseDisabled && this.autoplay){
            this.clearAutoPlay();
        }
    }

    handleOnMouseLeave(){
        if(!this.autopauseDisabled && this.autoplay){
            this.__autoPlay();
        }
    }

    getAriaControlsId(index:number){
        return `${this.id}-item-${index}`;
    }

    getIndicatorAriaLabel(index:number){
        return formatFn(this.accessibility.indicator, [index + 1]);
    }

    getSlideAriaLabel(index:number){
        return formatFn(this.accessibility.slide, [index + 1, this.cqItemsOrder.length]);
    }

    getSlideCssClass(index:number){
        return (this.activeIndex === index) ? `${this.class}__item ${this.class}__item--active` :  `${this.class}__item`;
    }

    getIndicatorCssClass(index:number){
        return (this.activeIndex === index) ? `${this.class}__indicator ${this.class}__indicator--active` : `${this.class}__indicator`;
    }

    handleOnButtonPrev(){
        this.prevSlide();
    }

    handleOnButtonNext(){
        this.nextSlide();
    }

    handleIndicatorClick(index){
        this.activeIndex = index;
    }

    __autoPlay(){
        this.interval = setInterval(() => {
            this.autoPlayTick();
        }, this.delay);
    }

    autoPlayTick() {

        if (!this.autoplay || this.cqItemsOrder.length <= 1) {
            return;
        }

        this.nextSlide();
    };

    clearAutoPlay = () => {
        clearInterval(this.interval);
    };

    toggleAutoPlay(toggle){
        this.autoplay = toggle;
    }

    nextSlide(){

        const activeIndex = this.__getActiveIndex();

        if(activeIndex=== (this.cqItemsOrder.length-1)){

            this.__setSlide(0);
        }else{
            this.__setSlide(activeIndex + 1);
        }
    }

    prevSlide(){
        const activeIndex = this.__getActiveIndex();
        if(activeIndex === 0){

            this.__setSlide(this.cqItemsOrder.length - 1);
        }else{
            this.__setSlide(activeIndex - 1);
        }
    }

    __getActiveIndex(){
        return this.activeIndex;
    }

    __setSlide(index){
        this.activeIndex = index;
    }
}
<ng-container *ngIf="isAllowedComponentsApplicable(); else container">
    <div [class]="getAllowedComponentListPlaceholderClassNames()">
        <div [attr.data-text]="getAllowedComponentListLabel()" [class]="allowedComponentListTitleClassNames"></div>
        <ng-container *ngFor="let allowedComponent of getAllowedComponents()">
            <div [attr.data-cq-data-path]="allowedComponent.path"
                 [attr.data-emptytext]="allowedComponent.title"
                 [class]="allowedComponentClassNames"></div>
        </ng-container>
    </div>
</ng-container>
<ng-template #container>
    
    <div class="carousel">
        <div id="{{id}}" class="{{class}}" role="group" [attr.aria-roledescription]="accessibilityLabel">
            <div class="{{class}}__content" (mouseenter)="handleOnMouseEnter()" (mouseleave)="handleOnMouseLeave()"
            >
                <div *ngFor="let itemKey of cqItemsOrder; let i = index"
                     [class]="getSlideCssClass(i)"
                     id="{{id}}-item-{{i}}"
                     role="tabpanel"
                     [attr.aria-label]="getSlideAriaLabel(i)">
                    <div
                            [aemModelProvider]
                            [cqItem]="getItem(itemKey)"
                            [cqPath]="getDataPath(itemKey)"
                            [itemName]="itemKey"
                            [attr.data-cq-data-path]="getDataPath(itemKey)"></div>
                </div>
                
                <div class="{{class}}__actions">
                    <button class="{{class}}__action {{class}}__action--previous"
                            type="button"
                            [attr.aria-label]="accessibility.previous"
                            (click)="handleOnButtonPrev()">
                        <span class="{{class}}__action-icon"></span>
                        <span class="{{class}}__action-text" [innerText]="accessibility.previous"></span>
                    </button>
                    <button class="{{class}}__action {{class}}__action--next"
                            type="button"
                            [attr.aria-label]="accessibility.next"
                            (click)="handleOnButtonNext()">
                        <span class="{{class}}__action-icon"></span>
                        <span class="{{class}}__action-text" [innerText]="accessibility.next"></span>
                    </button>
                
                </div>
                <ol class="{{class}}__indicators" role="tablist" [attr.aria-label]="accessibility.indicators">
                    <li *ngFor="let itemKey of cqItemsOrder; let i = index"
                        [class]="getIndicatorCssClass(i)"
                        role="tab"
                        (click)="handleIndicatorClick(i)"
                        [attr.aria-controls]="getAriaControlsId(i)"
                        [attr.aria-label]="getIndicatorAriaLabel(i)" [innerText]="cqItems[itemKey]['cq:panelTitle']"></li>
                </ol>
            </div>
        
        </div>
    </div>
    
    <div *ngIf="isInEditMode;"
         [attr.data-cq-data-path]="placeholderPath"
         [class]="getPlaceholderClassNames()">
    </div>
    
</ng-template>
